### ISSUE TITLE
Data is empty

### ISSUE THREAD

**Issue by zsapkagy** [datorama/akita-ng-router-store#1]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Router's data is always empty in the store

```
//app-routing.module.ts
{
    path: 'data',
    component: RouterDataComponent,
    data: { title: 'Router.Data.Title' }
}

//router-data.component.ts
this.routeQuery.select(state => state.state.root.data).subscribe(data => {
     console.log(data)); // {}
}
```

## Expected behavior
I would like to access the data property that was defined statically at the current route's definition.
```
//router-data.component.ts
this.routeQuery.select(state => state.state.root.data).subscribe(data => {
    console.log(data)); // 'Router.Data.Title'
}
```

## Minimal reproduction of the problem with instructions
I have been experimenting with this in the main repo's playground app. There is a routerStore so It was easy to try this out. So if it is required I can publish a feature branch there.

## What is the motivation / use case for changing the behavior?
I don't know what could the current data parameter contain with the current serialization logic. But I would be happier if it would hold the data for the actual route.

I see three possible solutions:

1. This is not a bug. :)
2. If this is a bug, and the corrected behavior is enough, than it can be easily fixed in the _RouterService.serializeRoute_ method like this:
```
return {
      url: route.url,
      params,
      queryParams: route.queryParams,
      fragment: route.fragment,
      // data: route.data,
      data: state.data,
      paramMap: route.paramMap,
      queryParamMap: route.queryParamMap
    };
```
3. I can imagine more complex scenarios where an overwritable serializer would be the solution (someting like the NgRx's CustomRouterStateSerializer) but it seems overkill for me in most of the cases.

**Comment by NetanelBasal** [comment]
Fixed in 1.0.1
