### ISSUE TITLE
Version on NPM does not match source?

### ISSUE THREAD

**Issue by tanepiper** [datorama/akita-ng-router-store#10]
Hi @NetanelBasal I was doing a dependency update and noticed that I got this upgrade suggestion:

`@datorama/akita-ng-router-store     ^3.1.3  →     ^4.0.0`

As I wanted to check changelogs I looked on here, but I see that the last published version from source was 3.1.3, and don't see a branch.  Are you aware of this?

If it's genuine then is there a changelog for a major bump?

**Comment by NetanelBasal** [comment]
The only update is that we don't need the `.forRoot()` anymore:

`AkitaNgRouterStoreModule.forRoot() => AkitaNgRouterStoreModule`

**Comment by tanepiper** [comment]
@NetanelBasal OK thank you for confirming - with issues on NPM before with hacked packages I wanted to make sure before I updated the version that it's a valid release.
