### ISSUE TITLE
NavigationExtras.state (history.state) is not stored in the store

### ISSUE THREAD

**Issue by luiswk** [datorama/akita-ng-router-store#11]
Hello Netanel,

First of all thanks for great work on Akita. We have been using it successfully in our commercial project for a while now without any problems.

Recently I have run into this Router store and I am planning to use it for my case, but wanted to ask if there is any reason why you don't store the https://angular.io/api/router/NavigationExtras#state property in the store?

Thanks for answering,
Wojtek

**Comment by NetanelBasal** [comment]
No particular reason I think, do you want to create a PR and add it?

**Comment by luiswk** [comment]
OK no problem, I will give it a try!

**Comment by NetanelBasal** [comment]
Please do it in the official repo.

**Comment by NetanelBasal** [comment]
Added in v5. https://github.com/datorama/akita/blob/master/angular/playground/projects/ng-router-store/BREAKING_CHANGES.md
