### ISSUE TITLE
Why are all methods generics?

### ISSUE THREAD

**Issue by Benny739** [datorama/akita-ng-router-store#13]
I'm wondering why all the methods of RouterQuery are generics. 
```
selectParams<T>(names: string[]): Observable<T[]>;
```
I can't see when a param would not be a string? I think it would at least make sense to make string the default, and whenever you want you can just provide sth else. But without a default we get unknown and we have to specifiy string everytime.

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.

**Comment by Benny739** [comment]
Submitted a PR #14
