### ISSUE TITLE
Update to support rxjs 7.0

### ISSUE THREAD

**Issue by mhosman** [datorama/akita-ng-router-store#19]

**Comment by mhosman** [comment]
@NetanelBasal this repo is deprecated? Nobody is answering to tickets.

**Comment by NetanelBasal** [comment]
<img width="1006" alt="Screen Shot 2021-06-11 at 8 37 47" src="https://user-images.githubusercontent.com/6745730/121636252-4fed8680-ca90-11eb-8b62-0dafc61020eb.png">

**Comment by mhosman** [comment]
Okay thanks @NetanelBasal, I'll close this ticket. We need to update the documentation because this package is still being referenced. I can push a PR with that change if you want to. Sorry for the other message but I was just trying to know what was happening, was not my intention to be rude. Thanks man!
