### ISSUE TITLE
Router store error

### ISSUE THREAD

**Issue by pickaneym** [datorama/akita-ng-router-store#3]
![image](https://user-images.githubusercontent.com/29157221/54522152-7b639280-49a7-11e9-9574-0bbc02504214.png)

![image](https://user-images.githubusercontent.com/29157221/54522030-3c354180-49a7-11e9-9de1-b829110a53c4.png)

![image](https://user-images.githubusercontent.com/29157221/54522244-b5349900-49a7-11e9-8fe7-44b7853066de.png)

Installed dev tools and router store -> imported in app module then get this error.

**Comment by pickaneym** [comment]
Fixed by reinstalling router store package.

**Comment by NetanelBasal** [comment]
Why reopen?

**Comment by NetanelBasal** [comment]
You need to upgrade the router store to v3.

**Comment by pickaneym** [comment]
@NetanelBasal oh okay, so akita cli installs old version by default.

**Comment by NetanelBasal** [comment]
If you are talking about `ng-add`, no. It installs the latest version. https://github.com/datorama/akita/blob/master/schematics/src/ng-add/index.ts#L26
