### ISSUE TITLE
@datorama/akita-ng-router-store@3.0.1" has incorrect peer dependency "@datorama/akita@3.4.0"

### ISSUE THREAD

**Issue by micobarac** [datorama/akita-ng-router-store#4]
@datorama/akita-ng-router-store@3.0.1" has incorrect peer dependency "@datorama/akita@3.4.0"

I am using "@datorama/akita": "^3.6.0"

**Comment by NetanelBasal** [comment]
@shaharkazaz

**Comment by micobarac** [comment]
```ts
import { AkitaNgDevtools } from '@datorama/akita';
import { AkitaNgRouterStoreModule } from '@datorama/akita-ng-router-store';
```

@datorama/akita/datorama-akita"' has no exported member 'AkitaNgDevtools'. Did you mean 'akitaDevtools'?

**Comment by NetanelBasal** [comment]
No, it's `@datorama/akita-ngdevtools`, I'm releasing a fix. Thanks.
