### ISSUE TITLE
@datorama/akita-ng-router-store@3.0.2 requires a peer of @datorama/akita@^3.4.0

### ISSUE THREAD

**Issue by snebjorn** [datorama/akita-ng-router-store#5]
> npm WARN @datorama/akita-ng-router-store@3.0.2 requires a peer of @datorama/akita@^3.4.0 but none is installed. You must install peer dependencies yourself.

`@datorama/akita@^4.1.0` is out

**Comment by NetanelBasal** [comment]
Fixed in v3.0.3.
