### ISSUE TITLE
getQueryParams is returning Params

### ISSUE THREAD

**Issue by mpaul31** [datorama/akita-ng-router-store#6]
When calling `getQueryParams` it is returning the values from `Params` and not `QueryParams`. Looked at the source to confirm.

also, after resetting the router store, all the `GetXXX` methods return a null reference exception because the state property is null.

Thanks,

**Comment by NetanelBasal** [comment]
- Fixed the `QueryParams` issue.
- This is the default value of Angular's router. We have the [protection](https://github.com/datorama/akita-ng-router-store/blob/master/src/router.query.ts#L49) in the code.
