### ISSUE TITLE
Using with persistState()

### ISSUE THREAD

**Issue by step4** [datorama/akita-ng-router-store#7]
I try to persist my router state with 
```
(main.js)

persistState({
  include: ['session', 'router'],
  preStorageUpdateOperator: () => debounceTime(500)
})
```

but the last route is not always saved.
When I look on the state with the Redux DevTools, it seems that the route is not updated.

**Comment by NetanelBasal** [comment]
Why do you need to persist the router state? It doesn't make sense, as Angular will always override it.

**Comment by step4** [comment]
I tried to use it in an ionic app. So when I restart the application the user can start where they left

**Comment by NetanelBasal** [comment]
Akita doesn't change the current location. It just stores the data. You need to do it yourself.

**Comment by step4** [comment]
Yeah but it seams to work if the state has a url saved.
So I guess angular is redirecting to that location.

Interesting is without the persisting state for the router, the router changes are recognized:
![router1](https://user-images.githubusercontent.com/11348121/62450652-05e93a80-b76d-11e9-8d0a-7325a3391fc3.PNG)

but when I add the router state to the persistState function, the changes are not recognized

**Comment by step4** [comment]
So I guess I will persist the last route differently
